name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install sphinx==5.1.1 sphinx_rtd_theme sphinx-favicon myst_parser
      - name: Sphinx build
        run: |
          sphinx-build doc _build
      - name: Set branch name
        id: branch
        run: echo "::set-output name=BRANCH_NAME::${GITHUB_REF##*/}"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          destination_dir: ${( steps.branch.outputs.BRANCH_NAME }}
          force_orphan: true
          full_commit_message: Deploy documentation of branch ${( steps.branch.outputs.BRANCH_NAME }} to GitHub Pages
